## Loan Approval Prediction

In [1]:
## import the pandas and numpy library
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
## Import and read the first five records of the train data set
train_data_set = pd.read_csv("train.csv")
train_data_set.head()

id  person_age  person_income person_home_ownership  person_emp_length  \
0   0          37          35000                  RENT                0.0   
1   1          22          56000                   OWN                6.0   
2   2          29          28800                   OWN                8.0   
3   3          30          70000                  RENT               14.0   
4   4          22          60000                  RENT                2.0   

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_percent_income  \
0   EDUCATION          B       6000          11.49                 0.17   
1     MEDICAL          C       4000          13.35                 0.07   
2    PERSONAL          A       6000           8.90                 0.21   
3     VENTURE          B      12000          11.11                 0.17   
4     MEDICAL          A       6000           6.92                 0.10   

  cb_person_default_on_file  cb_person_cred_hist_length  loan_status  
0                         N                          14            0  
1                         N                           2            0  
2                         N                          10            0  
3                         N                           5            0  
4                         N                           3            0

In [3]:
## import and read the first five records of the test data set 

In [4]:
test_data_set = pd.read_csv("test.csv")
test_data_set.head()

id  person_age  person_income person_home_ownership  person_emp_length  \
0  58645          23          69000                  RENT                3.0   
1  58646          26          96000              MORTGAGE                6.0   
2  58647          26          30000                  RENT                5.0   
3  58648          33          50000                  RENT                4.0   
4  58649          26         102000              MORTGAGE                8.0   

         loan_intent loan_grade  loan_amnt  loan_int_rate  \
0    HOMEIMPROVEMENT          F      25000          15.76   
1           PERSONAL          C      10000          12.68   
2            VENTURE          E       4000          17.19   
3  DEBTCONSOLIDATION          A       7000           8.90   
4    HOMEIMPROVEMENT          D      15000          16.32   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.36                         N                           2  
1                 0.10                         Y                           4  
2                 0.13                         Y                           2  
3                 0.14                         N                           7  
4                 0.15                         Y                           4

In [5]:
## Get the informattion about the train dataset

In [6]:
train_data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   id                          58645 non-null  int64  
 1   person_age                  58645 non-null  int64  
 2   person_income               58645 non-null  int64  
 3   person_home_ownership       58645 non-null  object 
 4   person_emp_length           58645 non-null  float64
 5   loan_intent                 58645 non-null  object 
 6   loan_grade                  58645 non-null  object 
 7   loan_amnt                   58645 non-null  int64  
 8   loan_int_rate               58645 non-null  float64
 9   loan_percent_income         58645 non-null  float64
 10  cb_person_default_on_file   58645 non-null  object 
 11  cb_person_cred_hist_length  58645 non-null  int64  
 12  loan_status                 58645 non-null  int64  
dtypes: float64(3), int64(6), object

In [7]:
## check the value counts of the target variable

In [8]:
train_data_set['loan_status'].value_counts()

loan_status
0    50295
1     8350
Name: count, dtype: int64

In [9]:
## Get the summary statistics of the dataset

In [10]:
train_data_set.describe()

id    person_age  person_income  person_emp_length  \
count  58645.000000  58645.000000   5.864500e+04       58645.000000   
mean   29322.000000     27.550857   6.404617e+04           4.701015   
std    16929.497605      6.033216   3.793111e+04           3.959784   
min        0.000000     20.000000   4.200000e+03           0.000000   
25%    14661.000000     23.000000   4.200000e+04           2.000000   
50%    29322.000000     26.000000   5.800000e+04           4.000000   
75%    43983.000000     30.000000   7.560000e+04           7.000000   
max    58644.000000    123.000000   1.900000e+06         123.000000   

          loan_amnt  loan_int_rate  loan_percent_income  \
count  58645.000000   58645.000000         58645.000000   
mean    9217.556518      10.677874             0.159238   
std     5563.807384       3.034697             0.091692   
min      500.000000       5.420000             0.000000   
25%     5000.000000       7.880000             0.090000   
50%     8000.000000      10.750000             0.140000   
75%    12000.000000      12.990000             0.210000   
max    35000.000000      23.220000             0.830000   

       cb_person_cred_hist_length   loan_status  
count                58645.000000  58645.000000  
mean                     5.813556      0.142382  
std                      4.029196      0.349445  
min                      2.000000      0.000000  
25%                      3.000000      0.000000  
50%                      4.000000      0.000000  
75%                      8.000000      0.000000  
max                     30.000000      1.000000

## Explotary Data Analysis (EDA) for training dataset

In [11]:
train_data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   id                          58645 non-null  int64  
 1   person_age                  58645 non-null  int64  
 2   person_income               58645 non-null  int64  
 3   person_home_ownership       58645 non-null  object 
 4   person_emp_length           58645 non-null  float64
 5   loan_intent                 58645 non-null  object 
 6   loan_grade                  58645 non-null  object 
 7   loan_amnt                   58645 non-null  int64  
 8   loan_int_rate               58645 non-null  float64
 9   loan_percent_income         58645 non-null  float64
 10  cb_person_default_on_file   58645 non-null  object 
 11  cb_person_cred_hist_length  58645 non-null  int64  
 12  loan_status                 58645 non-null  int64  
dtypes: float64(3), int64(6), object

In [12]:
train_data_set['person_home_ownership'].value_counts()

person_home_ownership
RENT        30594
MORTGAGE    24824
OWN          3138
OTHER          89
Name: count, dtype: int64

In [13]:
train_data_set['loan_intent'].value_counts()

loan_intent
EDUCATION            12271
MEDICAL              10934
PERSONAL             10016
VENTURE              10011
DEBTCONSOLIDATION     9133
HOMEIMPROVEMENT       6280
Name: count, dtype: int64

In [14]:
train_data_set['loan_grade'].value_counts()

loan_grade
A    20984
B    20400
C    11036
D     5034
E     1009
F      149
G       33
Name: count, dtype: int64

In [15]:
train_data_set['cb_person_default_on_file'].value_counts()

cb_person_default_on_file
N    49943
Y     8702
Name: count, dtype: int64

In [16]:
## Data Preprcoessing

In [17]:
## when we consider the training set you can see categorical text oriented variables are there. So the, when we give that kind of features for model training,
## we have to convert into numeric values

In [18]:
train_data_set_new=train_data_set.replace({'person_home_ownership' :{'RENT':0, 'MORTGAGE':2, 'OWN':3,'OTHER':4}, 
                   'loan_intent':{'EDUCATION':1, 'MEDICAL':2,'PERSONAL':3, 'VENTURE':4,'DEBTCONSOLIDATION':5, 'HOMEIMPROVEMENT':6},
                   'loan_grade':{'A':1,'B':2,'C':3,'D':4,'E':5,'F':6,'G':7}, 'cb_person_default_on_file':{'N':0,'Y':1}})
train_data_set_new.head()

id  person_age  person_income  person_home_ownership  person_emp_length  \
0   0          37          35000                      0                0.0   
1   1          22          56000                      3                6.0   
2   2          29          28800                      3                8.0   
3   3          30          70000                      0               14.0   
4   4          22          60000                      0                2.0   

   loan_intent  loan_grade  loan_amnt  loan_int_rate  loan_percent_income  \
0            1           2       6000          11.49                 0.17   
1            2           3       4000          13.35                 0.07   
2            3           1       6000           8.90                 0.21   
3            4           2      12000          11.11                 0.17   
4            2           1       6000           6.92                 0.10   

   cb_person_default_on_file  cb_person_cred_hist_length  loan_status  
0                          0                          14            0  
1                          0                           2            0  
2                          0                          10            0  
3                          0                           5            0  
4                          0                           3            0

In [19]:
## Plot the training dataset based on loan_status  using scatterplots

In [20]:
#import seaborn as sns

#sns.pairplot(train_data_set_new, hue="loan_status")

In [21]:
## check the correlational coefficiancy between dependent variable and independent variables

In [22]:
train_set_new_corr = train_data_set_new.corr()

In [23]:
train_set_new_corr

id  person_age  person_income  \
id                          1.000000    0.008608      -0.001896   
person_age                  0.008608    1.000000       0.102176   
person_income              -0.001896    0.102176       1.000000   
person_home_ownership       0.003036    0.049147       0.231942   
person_emp_length           0.005376    0.121276       0.164042   
loan_intent                -0.004417    0.100919       0.074045   
loan_grade                 -0.002184    0.016497      -0.059279   
loan_amnt                  -0.000403    0.050378       0.310942   
loan_int_rate              -0.003454    0.009653      -0.057611   
loan_percent_income        -0.002677   -0.031975      -0.280314   
cb_person_default_on_file  -0.001681    0.004408      -0.035514   
cb_person_cred_hist_length  0.008139    0.874260       0.082727   
loan_status                -0.008138   -0.001130      -0.169956   

                            person_home_ownership  person_emp_length  \
id                                       0.003036           0.005376   
person_age                               0.049147           0.121276   
person_income                            0.231942           0.164042   
person_home_ownership                    1.000000           0.269834   
person_emp_length                        0.269834           1.000000   
loan_intent                              0.055369           0.048419   
loan_grade                              -0.166610          -0.091514   
loan_amnt                                0.092894           0.092046   
loan_int_rate                           -0.182281          -0.101910   
loan_percent_income                     -0.128426          -0.065824   
cb_person_default_on_file               -0.087478          -0.054467   
cb_person_cred_hist_length               0.044978           0.102842   
loan_status                             -0.239073          -0.100428   

                            loan_intent  loan_grade  loan_amnt  loan_int_rate  \
id                            -0.004417   -0.002184  -0.000403      -0.003454   
person_age                     0.100919    0.016497   0.050378       0.009653   
person_income                  0.074045   -0.059279   0.310942      -0.057611   
person_home_ownership          0.055369   -0.166610   0.092894      -0.182281   
person_emp_length              0.048419   -0.091514   0.092046      -0.101910   
loan_intent                    1.000000    0.013440   0.049246       0.003821   
loan_grade                     0.013440    1.000000   0.113273       0.935837   
loan_amnt                      0.049246    0.113273   1.000000       0.113582   
loan_int_rate                  0.003821    0.935837   0.113582       1.000000   
loan_percent_income           -0.016012    0.153865   0.647266       0.152201   
cb_person_default_on_file      0.004162    0.550677   0.020271       0.501841   
cb_person_cred_hist_length     0.085549    0.012276   0.045720       0.007535   
loan_status                    0.041541    0.385908   0.144982       0.338948   

                            loan_percent_income  cb_person_default_on_file  \
id                                    -0.002677                  -0.001681   
person_age                            -0.031975                   0.004408   
person_income                         -0.280314                  -0.035514   
person_home_ownership                 -0.128426                  -0.087478   
person_emp_length                     -0.065824                  -0.054467   
loan_intent                           -0.016012                   0.004162   
loan_grade                             0.153865                   0.550677   
loan_amnt                              0.647266                   0.020271   
loan_int_rate                          0.152201                   0.501841   
loan_percent_income                    1.000000                   0.042979   
cb_person_default_on_file              0.042979                   1.000000   
cb_person_cred_

In [24]:
## check the null values of the train_set_new

In [26]:
train_data_set_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   id                          58645 non-null  int64  
 1   person_age                  58645 non-null  int64  
 2   person_income               58645 non-null  int64  
 3   person_home_ownership       58645 non-null  int64  
 4   person_emp_length           58645 non-null  float64
 5   loan_intent                 58645 non-null  int64  
 6   loan_grade                  58645 non-null  int64  
 7   loan_amnt                   58645 non-null  int64  
 8   loan_int_rate               58645 non-null  float64
 9   loan_percent_income         58645 non-null  float64
 10  cb_person_default_on_file   58645 non-null  int64  
 11  cb_person_cred_hist_length  58645 non-null  int64  
 12  loan_status                 58645 non-null  int64  
dtypes: float64(3), int64(10)
memory

In [ ]:
## seperate the independent variables and independent variables from train_set

In [28]:
X = train_data_set_new.iloc[:,0:12]
X.head()

id  person_age  person_income  person_home_ownership  person_emp_length  \
0   0          37          35000                      0                0.0   
1   1          22          56000                      3                6.0   
2   2          29          28800                      3                8.0   
3   3          30          70000                      0               14.0   
4   4          22          60000                      0                2.0   

   loan_intent  loan_grade  loan_amnt  loan_int_rate  loan_percent_income  \
0            1           2       6000          11.49                 0.17   
1            2           3       4000          13.35                 0.07   
2            3           1       6000           8.90                 0.21   
3            4           2      12000          11.11                 0.17   
4            2           1       6000           6.92                 0.10   

   cb_person_default_on_file  cb_person_cred_hist_length  
0                          0                          14  
1                          0                           2  
2                          0                          10  
3                          0                           5  
4                          0                           3

In [30]:
y=train_data_set_new.iloc[:,12]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: loan_status, dtype: int64

## Split the training data into training and test set

In [31]:
from sklearn.model_selection import train_test_split

x_train_new, x_test_new,y_train_new, y_test_new = train_test_split(X,y, test_size=0.2, random_state=42)
x_train_new.head()

id  person_age  person_income  person_home_ownership  \
14337  14337          36          50000                      0   
17117  17117          27          43200                      0   
32590  32590          25          70000                      2   
55811  55811          39          75000                      2   
40120  40120          22          45600                      0   

       person_emp_length  loan_intent  loan_grade  loan_amnt  loan_int_rate  \
14337                0.0            6           3       7200          13.85   
17117                3.0            5           3       5000          11.66   
32590                0.0            1           1       8000           7.88   
55811                2.0            5           1      15000           6.54   
40120                5.0            2           1       4000           7.66   

       loan_percent_income  cb_person_default_on_file  \
14337                 0.14                          1   
17117                 0.12                          1   
32590                 0.11                          0   
55811                 0.20                          0   
40120                 0.09                          0   

       cb_person_cred_hist_length  
14337                          15  
17117                           9  
32590                           3  
55811                          11  
40120                           2

In [32]:
x_test_new.head()

id  person_age  person_income  person_home_ownership  \
4657    4657          23          40000                      0   
56440  56440          25          60000                      2   
42117  42117          32          66300                      0   
10849  10849          22          30000                      0   
39395  39395          27          60000                      0   

       person_emp_length  loan_intent  loan_grade  loan_amnt  loan_int_rate  \
4657                 0.0            2           1       3700           8.00   
56440                9.0            6           1       5000           8.59   
42117                0.0            2           2      20000          12.53   
10849                0.0            5           2       5000          10.59   
39395                1.0            2           2       7000          12.21   

       loan_percent_income  cb_person_default_on_file  \
4657                  0.09                          0   
56440                 0.08                          0   
42117                 0.26                          0   
10849                 0.17                          0   
39395                 0.12                          0   

       cb_person_cred_hist_length  
4657                            4  
56440                           4  
42117                           6  
10849                           2  
39395                          10

## Model Selection

In [ ]:
## DecisionTreeClassifier

In [33]:
from sklearn.tree import DecisionTreeClassifier

DTC = DecisionTreeClassifier()
DTC.fit(x_train_new,y_train_new)

DecisionTreeClassifier()

In [34]:
DTC_pred= DTC.predict(x_test_new)
DTC_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [35]:

DTC_accuracy = accuracy_score(y_test_new, DTC_pred)
DTC_accuracy

0.9105635604058318

In [36]:
DTC_confusion_matrix = confusion_matrix(y_test_new, DTC_pred)
DTC_confusion_matrix

array([[9502,  585],
       [ 464, 1178]], dtype=int64)

In [37]:
DTC_classification_report = classification_report(y_test_new, DTC_pred)
print(DTC_classification_report)

              precision    recall  f1-score   support

           0       0.95      0.94      0.95     10087
           1       0.67      0.72      0.69      1642

    accuracy                           0.91     11729
   macro avg       0.81      0.83      0.82     11729
weighted avg       0.91      0.91      0.91     11729



In [ ]:
## RandomForestClassifier

In [38]:
from sklearn.ensemble import RandomForestClassifier

RFC = RandomForestClassifier(n_estimators=400, criterion="entropy", max_features=30)
RFC.fit(x_train_new, y_train_new)

RandomForestClassifier(criterion='entropy', max_features=30, n_estimators=400)

In [39]:
RFC_prediction = RFC.predict(x_test_new)
RFC_prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [40]:
RFC_accuracy = accuracy_score(y_test_new,RFC_prediction)
RFC_accuracy

0.9517435416489044

In [41]:
RFC_confusion_matrix = confusion_matrix(y_test_new, RFC_prediction)
RFC_confusion_matrix

array([[9970,  117],
       [ 449, 1193]], dtype=int64)

In [42]:
RFC_classification_report = classification_report(y_test_new,RFC_prediction)
print(RFC_classification_report)

              precision    recall  f1-score   support

           0       0.96      0.99      0.97     10087
           1       0.91      0.73      0.81      1642

    accuracy                           0.95     11729
   macro avg       0.93      0.86      0.89     11729
weighted avg       0.95      0.95      0.95     11729



In [ ]:
## Support vector Machione Classifier

In [43]:
from sklearn.svm import SVC

SVC = SVC()
SVC.fit(x_train_new, y_train_new)

SVC()

In [44]:
SVC_predictions = SVC.predict(x_test_new)
SVC_predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [45]:
SVC_accuracy= accuracy_score(y_test_new, SVC_predictions)
SVC_accuracy

0.8600051155256203

In [46]:
SVC_confusion_matrix = confusion_matrix(y_test_new, SVC_predictions)
SVC_confusion_matrix

array([[10087,     0],
       [ 1642,     0]], dtype=int64)

In [47]:
SVC_classification_report = classification_report(y_test_new, SVC_predictions)
print(SVC_classification_report)

              precision    recall  f1-score   support

           0       0.86      1.00      0.92     10087
           1       0.00      0.00      0.00      1642

    accuracy                           0.86     11729
   macro avg       0.43      0.50      0.46     11729
weighted avg       0.74      0.86      0.80     11729



C:\Users\THIS PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\THIS PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\THIS PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

In [48]:
from sklearn.neighbors import KNeighborsClassifier

kneighbor_model = KNeighborsClassifier(n_neighbors=200)
kneighbor_model.fit(x_train_new, y_train_new)

KNeighborsClassifier(n_neighbors=200)

In [49]:
kneighbor_model_prediction = kneighbor_model.predict(x_test_new)
kneighbor_model_prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
kneighbor_model_accuracy = accuracy_score(y_test_new, kneighbor_model_prediction)
kneighbor_model_accuracy

0.8744138460226788

In [51]:
kneighbor_model_confusion_matrix = confusion_matrix(y_test_new, kneighbor_model_prediction)
kneighbor_model_confusion_matrix

array([[10002,    85],
       [ 1388,   254]], dtype=int64)

In [52]:
kneighbor_model_classification_report = classification_report(y_test_new, kneighbor_model_prediction)
print(kneighbor_model_classification_report)

              precision    recall  f1-score   support

           0       0.88      0.99      0.93     10087
           1       0.75      0.15      0.26      1642

    accuracy                           0.87     11729
   macro avg       0.81      0.57      0.59     11729
weighted avg       0.86      0.87      0.84     11729



In [53]:
DTC_accuracy

0.9105635604058318

In [54]:
RFC_accuracy

0.9517435416489044

In [55]:
SVC_accuracy

0.8600051155256203

In [56]:
kneighbor_model_accuracy

0.8744138460226788

In [ ]:
## According to the above accuracies of the models random forest classifier is better model

## Explotary Data Analysis For test dataset

In [57]:
test_data_set.head()

id  person_age  person_income person_home_ownership  person_emp_length  \
0  58645          23          69000                  RENT                3.0   
1  58646          26          96000              MORTGAGE                6.0   
2  58647          26          30000                  RENT                5.0   
3  58648          33          50000                  RENT                4.0   
4  58649          26         102000              MORTGAGE                8.0   

         loan_intent loan_grade  loan_amnt  loan_int_rate  \
0    HOMEIMPROVEMENT          F      25000          15.76   
1           PERSONAL          C      10000          12.68   
2            VENTURE          E       4000          17.19   
3  DEBTCONSOLIDATION          A       7000           8.90   
4    HOMEIMPROVEMENT          D      15000          16.32   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.36                         N                           2  
1                 0.10                         Y                           4  
2                 0.13                         Y                           2  
3                 0.14                         N                           7  
4                 0.15                         Y                           4

In [ ]:
## data preprocessing and cleaning part

In [58]:
test_data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39098 entries, 0 to 39097
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   id                          39098 non-null  int64  
 1   person_age                  39098 non-null  int64  
 2   person_income               39098 non-null  int64  
 3   person_home_ownership       39098 non-null  object 
 4   person_emp_length           39098 non-null  float64
 5   loan_intent                 39098 non-null  object 
 6   loan_grade                  39098 non-null  object 
 7   loan_amnt                   39098 non-null  int64  
 8   loan_int_rate               39098 non-null  float64
 9   loan_percent_income         39098 non-null  float64
 10  cb_person_default_on_file   39098 non-null  object 
 11  cb_person_cred_hist_length  39098 non-null  int64  
dtypes: float64(3), int64(5), object(4)
memory usage: 3.6+ MB


In [60]:
test_data_set_new=test_data_set.replace({'person_home_ownership' :{'RENT':0, 'MORTGAGE':2, 'OWN':3,'OTHER':4}, 
                   'loan_intent':{'EDUCATION':1, 'MEDICAL':2,'PERSONAL':3, 'VENTURE':4,'DEBTCONSOLIDATION':5, 'HOMEIMPROVEMENT':6},
                   'loan_grade':{'A':1,'B':2,'C':3,'D':4,'E':5,'F':6,'G':7}, 'cb_person_default_on_file':{'N':0,'Y':1}})
test_data_set_new.head()

id  person_age  person_income  person_home_ownership  person_emp_length  \
0  58645          23          69000                      0                3.0   
1  58646          26          96000                      2                6.0   
2  58647          26          30000                      0                5.0   
3  58648          33          50000                      0                4.0   
4  58649          26         102000                      2                8.0   

   loan_intent  loan_grade  loan_amnt  loan_int_rate  loan_percent_income  \
0            6           6      25000          15.76                 0.36   
1            3           3      10000          12.68                 0.10   
2            4           5       4000          17.19                 0.13   
3            5           1       7000           8.90                 0.14   
4            6           4      15000          16.32                 0.15   

   cb_person_default_on_file  cb_person_cred_hist_length  
0                          0                           2  
1                          1                           4  
2                          1                           2  
3                          0                           7  
4                          1                           4

In [64]:
test_data_set_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39098 entries, 0 to 39097
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   id                          39098 non-null  int64  
 1   person_age                  39098 non-null  int64  
 2   person_income               39098 non-null  int64  
 3   person_home_ownership       39098 non-null  int64  
 4   person_emp_length           39098 non-null  float64
 5   loan_intent                 39098 non-null  int64  
 6   loan_grade                  39098 non-null  int64  
 7   loan_amnt                   39098 non-null  int64  
 8   loan_int_rate               39098 non-null  float64
 9   loan_percent_income         39098 non-null  float64
 10  cb_person_default_on_file   39098 non-null  int64  
 11  cb_person_cred_hist_length  39098 non-null  int64  
dtypes: float64(3), int64(9)
memory usage: 3.6 MB


In [ ]:
## Making the predictions using test set

In [78]:
#	id	person_age	person_income	person_home_ownership	person_emp_length	loan_intent	loan_grade	loan_amnt	loan_int_rate	loan_percent_income	cb_person_default_on_file	cb_person_cred_hist_length
#	0	37	35000	RENT	0.0	EDUCATION	B	6000	11.49	0.17	N	14
# 	id	person_age	person_income	person_home_ownership	person_emp_length	loan_intent	loan_grade	loan_amnt	loan_int_rate	loan_percent_income	cb_person_default_on_file	cb_person_cred_hist_length	loan_status
# 	0	37	35000	RENT	0.0	EDUCATION	B	6000	11.49	0.17	N	14	

#	id	person_age	person_income	person_home_ownership	person_emp_length	loan_intent	loan_grade	loan_amnt	loan_int_rate	loan_percent_income	cb_person_default_on_file	cb_person_cred_hist_length	loan_status
#	10	30	78000	MORTGAGE	5.0	VENTURE	B	12800	10.59	0.17	N	5	
#person_age	person_income	person_home_ownership	person_emp_length	loan_intent	loan_grade	loan_amnt	loan_int_rate	loan_percent_income	cb_person_default_on_file	cb_person_cred_hist_length	loan_status
#	31	75000	MORTGAGE	2.0	VENTURE	B	15000	11.11	0.2	N	5	0

#  id	person_age	person_income	person_home_ownership	person_emp_length	loan_intent	loan_grade	loan_amnt	loan_int_rate	loan_percent_income	cb_person_default_on_file	cb_person_cred_hist_length
# 58645	23	69000	RENT	3.0	HOMEIMPROVEMENT	F	25000	15.76	0.36	N	

# id	person_age	person_income	person_home_ownership	person_emp_length	loan_intent	loan_grade	loan_amnt	loan_int_rate	loan_percent_income	cb_person_default_on_file	cb_person_cred_hist_length	loan_status
# 58644	31	75000	MORTGAGE	2.0	VENTURE	B	15000	11.11	0.2	N	5	

# id	person_age	person_income	person_home_ownership	person_emp_length	loan_intent	loan_grade	loan_amnt	loan_int_rate	loan_percent_income	cb_person_default_on_file	cb_person_cred_hist_length	loan_status
# 58641	28	28800	RENT	0.0	MEDICAL	C	10000	12.73	0.35	N	8	

sample_data = [[58641,28,28800,0,0.0,2,3,1000,12.73,0.35,0,8]]

predictions  = RFC.predict(sample_data)
if predictions[0] ==0:
    print("Loan is not approved")
else:
    print("Loan is approved")

Loan is approved


C:\Users\THIS PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [67]:
prediction = RFC.predict_proba(test_data_set_new)
prediction

array([[0.02  , 0.98  ],
       [0.9575, 0.0425],
       [0.4825, 0.5175],
       ...,
       [0.9775, 0.0225],
       [0.8175, 0.1825],
       [0.0725, 0.9275]])

In [ ]:
## store the  id for later use

In [69]:
id  = test_data_set_new["id"]

In [79]:
import pandas as pd

# Get predicted probabilities
prediction = RFC.predict(test_data_set_new)

# Create the submission DataFrame
submission = pd.DataFrame({
    'id': id,  
    'loan_Status': prediction  
})

# Save the DataFrame to a CSV file
submission.to_csv('submission.csv', index=False)


In [80]:
submission

id  loan_Status
0      58645            1
1      58646            0
2      58647            1
3      58648            0
4      58649            0
...      ...          ...
39093  97738            0
39094  97739            0
39095  97740            0
39096  97741            0
39097  97742            1

[39098 rows x 2 columns]